

networks:
  compliance-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

services:
  # Dapr Placement Service - Required for Workflows and Actors
  placement:
    image: "daprio/dapr:1.15.0"
    container_name: compliance-placement
    command: ["./placement", "-port", "50005"]
    ports:
      - "50005:50005"
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:50005/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3

  # Redis - Used for Dapr State Store and Pub/Sub
  redis:
    image: redis:7-alpine
    container_name: compliance-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL - Main database for compliance data
  postgres:
    image: postgres:15-alpine
    container_name: compliance-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adaptive Interface Frontend (Chainlit UI)
  adaptive-interface-frontend:
    build:
      context: ./adaptive-interface/frontend
      dockerfile: Dockerfile
    container_name: compliance-adaptive-interface-frontend
    ports:
      - "9150:9150" # Expose Chainlit UI port
    networks:
      - compliance-network
    restart: on-failure
    env_file:
      - ../.env
    environment:
      - DAPR_HTTP_PORT=3500 # Dapr sidecar HTTP port for frontend
      - DAPR_GRPC_PORT=50000 # Dapr sidecar gRPC port for frontend

  adaptive-interface-frontend-daprd:
    image: "daprio/dapr:1.15.0"
    container_name: compliance-adaptive-interface-frontend-daprd
    command:
      - "./daprd"
      - "-app-id"
      - "adaptive-interface-frontend"
      - "-app-port"
      - "9150"
      - "-dapr-http-port"
      - "3500"
      - "-dapr-grpc-port"
      - "50000"
      - "-placement-host-address"
      - "placement:50005"
      - "-resources-path"
      - "/components"
    volumes:
      - "./infrastructure/dapr-components/:/components"
    depends_on:
      - adaptive-interface-frontend
    network_mode: "service:adaptive-interface-frontend"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3500/v1.0/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Adaptive Interface Backend (FastAPI for Dapr interactions)
  adaptive-interface-backend:
    build:
      context: ./adaptive-interface/backend
      dockerfile: Dockerfile
    container_name: compliance-adaptive-interface-backend
    networks:
      - compliance-network
    restart: on-failure
    env_file:
      - ../.env
    environment:
      - DAPR_HTTP_PORT=3501
      - DAPR_GRPC_PORT=50001

  adaptive-interface-backend-daprd:
    image: "daprio/dapr:1.15.0"
    container_name: compliance-adaptive-interface-backend-daprd
    command:
      - "./daprd"
      - "-app-id"
      - "adaptive-interface-backend"
      - "-app-port"
      - "9160"
      - "-dapr-http-port"
      - "3501"
      - "-dapr-grpc-port"
      - "50001"
      - "-placement-host-address"
      - "placement:50005"
      - "-resources-path"
      - "/components"
    volumes:
      - "./infrastructure/dapr-components/:/components"
    depends_on:
      - adaptive-interface-backend
    network_mode: "service:adaptive-interface-backend"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3501/v1.0/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Workflow Agent
  workflow-agent:
    build:
      context: ./workflow-agent
      dockerfile: Dockerfile
    container_name: compliance-workflow-agent
    networks:
      - compliance-network
    restart: on-failure
    env_file:
      - ../.env
    environment:
      - DAPR_HTTP_PORT=3502
      - DAPR_GRPC_PORT=50002
      - DAPR_GRPC_ENDPOINT=compliance-workflow-agent-daprd:50002
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9170/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  workflow-agent-daprd:
    image: "daprio/dapr:1.15.0"
    container_name: compliance-workflow-agent-daprd
    command:
      - "./daprd"
      - "-app-id"
      - "workflow-agent"
      - "-app-port"
      - "9170"
      - "-dapr-http-port"
      - "3502"
      - "-dapr-grpc-port"
      - "50002"
      - "-placement-host-address"
      - "placement:50005"
      - "-resources-path"
      - "/components"
    volumes:
      - "./infrastructure/dapr-components/:/components"
    depends_on:
      - workflow-agent
    networks:
      - compliance-network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3502/v1.0/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Harvester Insights Agent
  harvester-agent:
    build:
      context: ./harvester-insights-agent
      dockerfile: Dockerfile
    container_name: compliance-harvester-agent
    
    networks:
      - compliance-network
    restart: on-failure
    env_file:
      - ../.env
    environment:
      - DAPR_HTTP_PORT=3503
      - DAPR_GRPC_PORT=50003
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9180/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  harvester-agent-daprd:
    image: "daprio/dapr:1.15.0"
    container_name: compliance-harvester-agent-daprd
    command:
      - "./daprd"
      - "-app-id"
      - "harvester-insights-agent"
      - "-app-port"
      - "9180"
      - "-dapr-http-port"
      - "3503"
      - "-dapr-grpc-port"
      - "50003"
      - "-placement-host-address"
      - "placement:50005"
      - "-resources-path"
      - "/components"
    volumes:
      - "./infrastructure/dapr-components/:/components"
    depends_on:
      - harvester-agent
    network_mode: "service:harvester-agent"
    restart: on-failure