# Local development secret store (file-based)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "/app/secrets/secrets.json"
  - name: nestedSeparator
    value: ":"
---
# Kubernetes secret store (for production)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secret-store
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
---
# HashiCorp Vault secret store (for enterprise)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault-secret-store
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "https://vault.example.com:8200"
  - name: vaultTokenMountPath
    value: "/var/run/secrets/dapr.io/vault"
  - name: vaultToken
    secretKeyRef:
      name: vault-token
      key: token
