apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-agent-backend
  labels:
    app: compliance-agent-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compliance-agent-backend
  template:
    metadata:
      labels:
        app: compliance-agent-backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "compliance-agent-backend"
        dapr.io/app-port: "9160"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: compliance-agent-backend
        image: thiago4go/adaptive-interface-backend:latest
        ports:
        - containerPort: 9160
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        - name: OPENAI_MODEL
          value: "gpt-4.1-nano"
        - name: LITERAL_DISABLE
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9160
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9160
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-agent-backend-service
spec:
  selector:
    app: compliance-agent-backend
  ports:
  - port: 9160
    targetPort: 9160
    name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptive-interface-frontend
  labels:
    app: adaptive-interface-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adaptive-interface-frontend
  template:
    metadata:
      labels:
        app: adaptive-interface-frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "adaptive-interface"
        dapr.io/app-port: "9150"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: adaptive-interface-frontend
        image: thiago4go/adaptive-interface-frontend:latest
        ports:
        - containerPort: 9150
          name: http
        env:
        - name: LITERAL_DISABLE
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9150
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9150
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: adaptive-interface-frontend-service
spec:
  selector:
    app: adaptive-interface-frontend
  ports:
  - port: 80
    targetPort: 9150
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adaptive-interface-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /hackathon
        pathType: Prefix
        backend:
          service:
            name: adaptive-interface-frontend-service
            port:
              number: 80
