apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: conversationstore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  - name: keyPrefix
    value: "conversation:"
scopes:
- harvester-insights-agent
