apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowstatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "compliance-redis:6379"  # Use compliance-redis service
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  - name: actorStateStore
    value: "true"
scopes:
- harvester-agent
- workflow-agent
