apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowstatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"  # Use localhost for local development
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  # Removed actorStateStore since agentstatestore is already the actor store
scopes:
- harvester-insights-agent
- workflow-agent
